name: "Wiz-lab - Appication CI/CD"

on:
  push:
    branches: [main, devtest]
  pull_request:
    branches: [main, devtest]

jobs:
  # STEP 1: BUILD & PUSH TO REGISTRY
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice applicativo
        uses: actions/checkout@v3

      - name: Login su Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push dell'immagine del Container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # ID del commit di Git per definire immagine univoca
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wiz-todo-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wiz-todo-app:${{ github.sha }}

  # STEP 2: TRIGGER KUBERNETES DEPLOYMENT
  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dei manifesti YAML
        uses: actions/checkout@v3

      - name: Configura credenziali AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Genera Kubeconfig per EKS
        run: aws eks update-kubeconfig --name wiz-demo-cluster

      # Sostituzione del tag dell'immagine nel manifesto con quello appena buildato + applica su Kubernetes
      - name: Deploy dei manifesti su Kubernetes
        run: |
          # Aggiorna il file deployment con il tag specifico del commit corrente
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/wiz-todo-app:${{ github.sha }}|g' k8s/todo-app-manifest.yaml
          
          # Applica i manifesti (Deployment, ServiceAccount con ClusterAdmin, Ingress)
          kubectl apply -f k8s/wiz-app-manifest.yaml
          
          # Forza Kubernetes ad attendere che il rollout del nuovo container sia completato
          kubectl rollout status deployment/todo-web-app --timeout=60s
